apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    clout.puccini.cloud/capability: job
    clout.puccini.cloud/vertex: _26vFVJUr5Lg9cylEjAPqpqZTEWJ
  labels:
    app: task-1
  name: task-1-job
  namespace: default
spec:
  template:
    spec:
      containers:
        - command: ["/bin/sh", "-c", "echo 'hello world'"]
          image: busybox
          name: task-1
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    clout.puccini.cloud/capability: job
    clout.puccini.cloud/vertex: _26vFVJx0t4fCy3DxXkcurpWcsQg
  labels:
    app: task-2
  name: task-2-job
  namespace: default
spec:
  template:
    spec:
      containers:
        - command: ["/bin/sh", "-c", "echo 'hello world'"]
          image: busybox
          name: task-2
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    clout.puccini.cloud/capability: job
    clout.puccini.cloud/vertex: _26vFVF7fMMUiB7SOFtKTptb5VxY
  labels:
    app: task-3
  name: task-3-job
  namespace: default
spec:
  template:
    spec:
      containers:
        - command: ["/bin/sh", "-c", "echo 'hello world'"]
          image: busybox
          name: task-3
